### ISSUE TITLE
[Task] Setup map editing environment

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/project-witch-one#42]
# Task Summary

The team has decided to use Tiled as the main map editing tool and completely separate the game scene logic from the level design. This means that the Tiled map editor must be configured to allow the map designer to easily work with the tool.

## Subtasks

This ticket will be considered as finished when the following items are fulfilled:

- [x] add object types for elements that will be read by the game (items, surface types, etc.)
- [x] configure terrain brushes for all the tilesets excluding ones we can't*
- [x] add object templates
- [x] set up automapping rules for all the cliff faces
- [x] write documentation about using Tiled for this project

(*The house tiles (both interiors and the exteriors) are only a single tile high while the player character sprite is 2 tiles high. So we should not touch the house tileset until this problem is solved)

## Difficulty

3/10

## Estimated Implementation Time

> Note: the task start date is considered to be the day the ticket was opened or the next day when the dependent task was closed

- **Optimistic**: 1 week
- **Normal**: 10 days
- **Pessimistic**: 2 weeks
